# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'MeasureUnit',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
                ('TotalCapacity', models.FloatField(default=0)),
                ('FK_Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Ingredient')),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackagesInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExistingPackagesQty', models.FloatField(default=0)),
                ('FK_Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileName', models.CharField(max_length=100, unique=True)),
                ('ProfileOwner', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Profile_has_Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekdayName', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miercoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sabado'), ('sunday', 'Domingo')], default='monday', max_length=50)),
                ('FK_Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Profile')),
            ],
            options={
                'db_table': 'Profile_has_Recipe',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('DayPosition', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='Recipe_has_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MUnitQty', models.FloatField()),
                ('PCS', models.FloatField(default=0)),
                ('FK_Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Ingredient')),
                ('FK_Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Recipe')),
            ],
            options={
                'db_table': 'Recipe_has_Ingredients',
            },
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StepName', models.CharField(max_length=150)),
                ('StepDescription', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'RecipeSteps',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='FK_Steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.RecipeSteps'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='FK_Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Tag'),
        ),
        migrations.AddField(
            model_name='profile_has_recipe',
            name='FK_Recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='FK_MUnit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.MeasureUnit'),
        ),
    ]
