# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-19 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AisleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'AisleTag',
            },
        ),
    ]
