# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_manager', '0002_aisletag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateMUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('EqQty', models.FloatField()),
                ('FK_Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_manager.Ingredient')),
            ],
            options={
                'db_table': 'AlternateMUnits',
            },
        ),
        migrations.AddField(
            model_name='measureunit',
            name='LongDescription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
